# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_app(object):
    def setupUi(self, mw_app):
        mw_app.setObjectName("mw_app")
        #mw_app.setWindowModality(QtCore.Qt.NonModal)
        mw_app.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(mw_app)
        self.centralwidget.setObjectName("centralwidget")
        self.l_logo = QtWidgets.QLabel(self.centralwidget)
        self.l_logo.setGeometry(QtCore.QRect(30, 30, 371, 221))
        self.l_logo.setText("")
        self.l_logo.setTextFormat(QtCore.Qt.AutoText)
        self.l_logo.setPixmap(QtGui.QPixmap("logo/logo_empresa.png"))
        self.l_logo.setScaledContents(True)
        self.l_logo.setObjectName("l_logo")
        self.l_usuario = QtWidgets.QLabel(self.centralwidget)
        self.l_usuario.setGeometry(QtCore.QRect(6, 1019, 621, 60))
        self.l_usuario.setObjectName("l_usuario")
        self.l_fecha_hora = QtWidgets.QLabel(self.centralwidget)
        self.l_fecha_hora.setGeometry(QtCore.QRect(1290, 1010, 621, 60))
        self.l_fecha_hora.setObjectName("l_fecha_hora")
        mw_app.setCentralWidget(self.centralwidget)

        self.retranslateUi(mw_app)
        QtCore.QMetaObject.connectSlotsByName(mw_app)

    def retranslateUi(self, mw_app):
        _translate = QtCore.QCoreApplication.translate
        mw_app.setWindowTitle(_translate("mw_app", "PhysioMRI_YMIR"))
        self.l_usuario.setText(_translate("mw_app", "TextLabel"))
        self.l_fecha_hora.setText(_translate("mw_app", "TextLabel"))
