# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/javier/physiomri/MaRGE/ui/ayuda_mod_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ayuda_mod_usuarios(object):
    def setupUi(self, ayuda_mod_usuarios):
        ayuda_mod_usuarios.setObjectName("ayuda_mod_usuarios")
        ayuda_mod_usuarios.resize(1920, 1080)
        self.frame = QtWidgets.QFrame(ayuda_mod_usuarios)
        self.frame.setGeometry(QtCore.QRect(410, 100, 501, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_home = QtWidgets.QPushButton(self.frame)
        self.btn_home.setGeometry(QtCore.QRect(380, 10, 112, 108))
        self.btn_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("template/black/volver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(100, 100))
        self.btn_home.setObjectName("btn_home")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 520, 71, 71))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("template/black/icono_cancelar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.l_editar = QtWidgets.QLabel(self.frame)
        self.l_editar.setGeometry(QtCore.QRect(90, 530, 391, 51))
        self.l_editar.setWordWrap(True)
        self.l_editar.setObjectName("l_editar")
        self.l_anyadir = QtWidgets.QLabel(self.frame)
        self.l_anyadir.setGeometry(QtCore.QRect(90, 450, 391, 51))
        self.l_anyadir.setTextFormat(QtCore.Qt.RichText)
        self.l_anyadir.setScaledContents(False)
        self.l_anyadir.setWordWrap(True)
        self.l_anyadir.setObjectName("l_anyadir")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 71, 71))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("template/black/icono_aceptar.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.l_texto = QtWidgets.QLabel(self.frame)
        self.l_texto.setGeometry(QtCore.QRect(10, 110, 481, 311))
        self.l_texto.setWordWrap(True)
        self.l_texto.setObjectName("l_texto")
        self.l_logo = QtWidgets.QLabel(ayuda_mod_usuarios)
        self.l_logo.setGeometry(QtCore.QRect(870, 420, 451, 201))
        self.l_logo.setText("")
        self.l_logo.setPixmap(QtGui.QPixmap("logo/logo_empresa.png"))
        self.l_logo.setObjectName("l_logo")
        self.fondo_sombra = QtWidgets.QPushButton(ayuda_mod_usuarios)
        self.fondo_sombra.setGeometry(QtCore.QRect(470, 850, 75, 23))
        self.fondo_sombra.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fondo_sombra.setText("")
        self.fondo_sombra.setFlat(False)
        self.fondo_sombra.setObjectName("fondo_sombra")
        self.l_usuario_acceso = QtWidgets.QLabel(ayuda_mod_usuarios)
        self.l_usuario_acceso.setGeometry(QtCore.QRect(0, 970, 621, 91))
        self.l_usuario_acceso.setText("")
        self.l_usuario_acceso.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.l_usuario_acceso.setObjectName("l_usuario_acceso")
        self.l_fecha_hora = QtWidgets.QLabel(ayuda_mod_usuarios)
        self.l_fecha_hora.setGeometry(QtCore.QRect(1295, 969, 621, 91))
        self.l_fecha_hora.setText("")
        self.l_fecha_hora.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.l_fecha_hora.setObjectName("l_fecha_hora")
        self.l_logo.raise_()
        self.fondo_sombra.raise_()
        self.frame.raise_()
        self.l_usuario_acceso.raise_()
        self.l_fecha_hora.raise_()

        self.retranslateUi(ayuda_mod_usuarios)
        QtCore.QMetaObject.connectSlotsByName(ayuda_mod_usuarios)
        ayuda_mod_usuarios.setTabOrder(self.fondo_sombra, self.btn_home)

    def retranslateUi(self, ayuda_mod_usuarios):
        _translate = QtCore.QCoreApplication.translate
        ayuda_mod_usuarios.setWindowTitle(_translate("ayuda_mod_usuarios", "Form"))
        self.l_editar.setText(_translate("ayuda_mod_usuarios", "<html><head/><body><p>Cancelar el alta y volver a la pantalla principal.</p></body></html>"))
        self.l_anyadir.setText(_translate("ayuda_mod_usuarios", "<html><head/><body><p>Aceptar el alta y volver a la pantalla principal.</p></body></html>"))
        self.l_texto.setText(_translate("ayuda_mod_usuarios", "<html><head/><body><p>Modificar datos del usuario.</p><p><br/></p><p>Podemos modificar datos del usuario. Nombre, contraseña y nivel de acceso.</p><p>Nivel Admin: no tiene restricciones de acceso.</p><p>Nivel User: tiene accesos restringidos. No tiene acceso a gestión usuarios y configuración de la aplicación.</p><p><br/></p></body></html>"))
