# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msg(object):
    def setupUi(self, msg):
        msg.setObjectName("msg")
        msg.resize(549, 287)
        self.frame = QtWidgets.QFrame(msg)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bnt_aceptar = QtWidgets.QPushButton(self.frame)
        self.bnt_aceptar.setGeometry(QtCore.QRect(210, 160, 112, 108))
        self.bnt_aceptar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bnt_aceptar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("template/black/icono_aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bnt_aceptar.setIcon(icon)
        self.bnt_aceptar.setIconSize(QtCore.QSize(100, 100))
        self.bnt_aceptar.setObjectName("bnt_aceptar")
        self.l_msg = QtWidgets.QLabel(self.frame)
        self.l_msg.setGeometry(QtCore.QRect(20, 10, 511, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.l_msg.setFont(font)
        self.l_msg.setLineWidth(1)
        self.l_msg.setMidLineWidth(0)
        self.l_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.l_msg.setWordWrap(True)
        self.l_msg.setObjectName("l_msg")
        self.fondo_sombra = QtWidgets.QPushButton(msg)
        self.fondo_sombra.setGeometry(QtCore.QRect(500, 240, 75, 23))
        self.fondo_sombra.setFocusPolicy(QtCore.Qt.NoFocus)
        #self.fondo_sombra.setText("")
        self.fondo_sombra.setFlat(False)
        self.fondo_sombra.setObjectName("fondo_sombra")
        self.fondo_sombra.raise_()
        self.frame.raise_()

        self.retranslateUi(msg)
        QtCore.QMetaObject.connectSlotsByName(msg)

    def retranslateUi(self, msg):
        _translate = QtCore.QCoreApplication.translate
        #msg.setWindowTitle(_translate("msg", "Form"))
        #self.l_msg.setText(_translate("msg", "Contraseña incorrecta ..."))
