# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName("frm_main")
        frm_main.resize(1920, 1077)
        self.l_logo = QtWidgets.QLabel(frm_main)
        self.l_logo.setGeometry(QtCore.QRect(560, 390, 451, 201))
        self.l_logo.setText("")
        self.l_logo.setPixmap(QtGui.QPixmap("logo/logo_empresa.png"))
        self.l_logo.setObjectName("l_logo")
        self.frame = QtWidgets.QFrame(frm_main)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1901, 151))
        #self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 149))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ly_menu_superior = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ly_menu_superior.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ly_menu_superior.setContentsMargins(20, 20, 20, 20)
        self.ly_menu_superior.setSpacing(20)
        self.ly_menu_superior.setObjectName("ly_menu_superior")
        self.btn_nuevo = QtWidgets.QPushButton(self.horizontalLayoutWidget) #self.horizontalLayoutWidget
        self.btn_nuevo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("template/black/nuevo_exp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nuevo.setIcon(icon)
        self.btn_nuevo.setIconSize(QtCore.QSize(100, 100))
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.ly_menu_superior.addWidget(self.btn_nuevo)
        self.btn_consultar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_consultar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("template/black/consultar_exp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_consultar.setIcon(icon1)
        self.btn_consultar.setIconSize(QtCore.QSize(100, 100))
        self.btn_consultar.setObjectName("btn_consultar")
        self.ly_menu_superior.addWidget(self.btn_consultar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ly_menu_superior.addItem(spacerItem)
        self.btn_usuarios = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_usuarios.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("template/black/gest_usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_usuarios.setIcon(icon2)
        self.btn_usuarios.setIconSize(QtCore.QSize(100, 100))
        self.btn_usuarios.setObjectName("btn_usuarios")
        self.ly_menu_superior.addWidget(self.btn_usuarios)
        self.btn_config = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_config.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("template/black/configuracion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_config.setIcon(icon3)
        self.btn_config.setIconSize(QtCore.QSize(100, 100))
        self.btn_config.setObjectName("btn_config")
        self.ly_menu_superior.addWidget(self.btn_config)
        self.btn_ayuda = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_ayuda.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("template/black/ayuda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ayuda.setIcon(icon4)
        self.btn_ayuda.setIconSize(QtCore.QSize(100, 100))
        self.btn_ayuda.setObjectName("btn_ayuda")
        self.ly_menu_superior.addWidget(self.btn_ayuda)
        self.btn_cerrar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cerrar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("template/black/usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon5)
        self.btn_cerrar.setIconSize(QtCore.QSize(100, 100))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.ly_menu_superior.addWidget(self.btn_cerrar)
        self.l_usuario_acceso = QtWidgets.QLabel(frm_main)
        self.l_usuario_acceso.setGeometry(QtCore.QRect(0, 970, 621, 91))
        self.l_usuario_acceso.setText("")
        self.l_usuario_acceso.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.l_usuario_acceso.setObjectName("l_usuario_acceso")
        self.l_fecha_hora = QtWidgets.QLabel(frm_main)
        self.l_fecha_hora.setGeometry(QtCore.QRect(1295, 969, 621, 91))
        self.l_fecha_hora.setText("")
        self.l_fecha_hora.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.l_fecha_hora.setObjectName("l_fecha_hora")

        self.retranslateUi(frm_main)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        _translate = QtCore.QCoreApplication.translate
        frm_main.setWindowTitle(_translate("frm_main", "PhysioMRI_YMIR"))
