# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/msgsn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msgsn(object):
    def setupUi(self, msgsn):
        msgsn.setObjectName("msgsn")
        msgsn.resize(547, 285)
        self.line = QtWidgets.QFrame(msgsn)
        self.line.setGeometry(QtCore.QRect(543, 10, 31, 281))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.fondo_sombra = QtWidgets.QPushButton(msgsn)
        self.fondo_sombra.setGeometry(QtCore.QRect(490, 260, 75, 23))
        self.fondo_sombra.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fondo_sombra.setText("")
        self.fondo_sombra.setFlat(False)
        self.fondo_sombra.setObjectName("fondo_sombra")
        self.frame = QtWidgets.QFrame(msgsn)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_cancelar = QtWidgets.QPushButton(self.frame)
        self.btn_cancelar.setGeometry(QtCore.QRect(280, 150, 112, 108))
        self.btn_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_cancelar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("template/black/icono_cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancelar.setIcon(icon)
        self.btn_cancelar.setIconSize(QtCore.QSize(100, 100))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_aceptar = QtWidgets.QPushButton(self.frame)
        self.btn_aceptar.setGeometry(QtCore.QRect(140, 150, 112, 108))
        self.btn_aceptar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_aceptar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("template/black/icono_aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_aceptar.setIcon(icon1)
        self.btn_aceptar.setIconSize(QtCore.QSize(100, 100))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.l_msg = QtWidgets.QLabel(self.frame)
        self.l_msg.setGeometry(QtCore.QRect(0, 0, 540, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.l_msg.setFont(font)
        self.l_msg.setLineWidth(1)
        self.l_msg.setMidLineWidth(0)
        self.l_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.l_msg.setWordWrap(True)
        self.l_msg.setObjectName("l_msg")
        self.fondo_sombra.raise_()
        self.frame.raise_()
        self.line.raise_()

        self.retranslateUi(msgsn)
        QtCore.QMetaObject.connectSlotsByName(msgsn)

    def retranslateUi(self, msgsn):
        _translate = QtCore.QCoreApplication.translate
        msgsn.setWindowTitle(_translate("msgsn", "Form"))
        self.l_msg.setText(_translate("msgsn", "Password incorrecto ..."))
