# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scan(object):
    def setupUi(self, scan):
        scan.setObjectName("scan")
        scan.resize(1920, 1080)
        self.frame = QtWidgets.QFrame(scan)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1681, 931))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l_pantalla = QtWidgets.QLabel(self.frame)
        self.l_pantalla.setGeometry(QtCore.QRect(10, 10, 1651, 911))
        self.l_pantalla.setText("")
        #self.l_pantalla.setPixmap(QtGui.QPixmap("ui\\../../../Users/Javier/Pictures/Screenshots/Captura de pantalla 2024-06-07 085423.png"))
        self.l_pantalla.setScaledContents(True)
        self.l_pantalla.setObjectName("l_pantalla")
        self.fondo_sombra = QtWidgets.QPushButton(scan)
        self.fondo_sombra.setGeometry(QtCore.QRect(10, 1050, 75, 23))
        self.fondo_sombra.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fondo_sombra.setText("")
        self.fondo_sombra.setFlat(False)
        self.fondo_sombra.setObjectName("fondo_sombra")
        self.l_fecha_hora = QtWidgets.QLabel(scan)
        self.l_fecha_hora.setGeometry(QtCore.QRect(1295, 969, 621, 91))
        self.l_fecha_hora.setText("")
        self.l_fecha_hora.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.l_fecha_hora.setObjectName("l_fecha_hora")
        self.l_usuario_acceso = QtWidgets.QLabel(scan)
        self.l_usuario_acceso.setGeometry(QtCore.QRect(0, 970, 621, 91))
        self.l_usuario_acceso.setText("")
        self.l_usuario_acceso.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.l_usuario_acceso.setObjectName("l_usuario_acceso")
        self.l_logo_2 = QtWidgets.QLabel(scan)
        self.l_logo_2.setGeometry(QtCore.QRect(1490, 420, 451, 201))
        self.l_logo_2.setText("")
        self.l_logo_2.setPixmap(QtGui.QPixmap("logo/logo_empresa.png"))
        self.l_logo_2.setObjectName("l_logo_2")
        self.l_logo_2.raise_()
        self.fondo_sombra.raise_()
        self.frame.raise_()
        self.l_fecha_hora.raise_()
        self.l_usuario_acceso.raise_()

        self.retranslateUi(scan)
        QtCore.QMetaObject.connectSlotsByName(scan)

    def retranslateUi(self, scan):
        _translate = QtCore.QCoreApplication.translate
        scan.setWindowTitle(_translate("scan", "Form"))
